### ISSUE TITLE
Moving towards general user usage?

### ISSUE THREAD

**Issue by drnic** [ECSTeam/cloudfoundry-top-plugin#2]
I saw https://twitter.com/mdcarlson/status/811262628483973120 and I tried to use `cf top` with my PWS account, but it fails:

![](https://cl.ly/00191t153T3T/download/Image%202016-12-21%20at%2012.21.36%20PM.png)

There aren't many "admins" per CF; and the plugin seems generally useful to all users.

What would it take in CF to allow this plugin to work on non-admin CF environments such as PWS or BlueMix?

**Comment by kkellner** [comment]
cf top requires that your have foundation "admin" privileges.   There is no way to get the information top needs without having nozzle access -- which requires admin privileges.

https://github.com/ECSTeam/cloudfoundry-top-plugin#assign-needed-permissions-if-not-using-admin-user

**Comment by drnic** [comment]
Could a new API be added to CF that uses the existing UAA auth token to return the information needed? Or could the subsystems you're already talking to - but currently only respond to "admin" - be upgraded to accept lesser authorization?






On Wed, Dec 21, 2016 at 11:59 AM +1000, "Kurt Kellner" <notifications@github.com> wrote:












cf top requires that your have foundation "admin" privileges.   There is no way to get the information top needs without having nozzle access -- which requires admin privileges.


https://github.com/ECSTeam/cloudfoundry-top-plugin#assign-needed-permissions-if-not-using-admin-user

**Comment by kkellner** [comment]
The information needed to get the live stats that top displays is from the firehose.  The firehose contains everything happening on the platform including all log messages from applications deployed in CF.  This information can be sensitive as applications can log anything.  I suspect that the choice to secure the firehose was purposeful.   If there was a way the traffic controller would only send firehose events appropriate to the user's access (i.g., orgs and spaces the user has access to) it might be possible to provide a limited view in top plugin.   However I suspect the performance penalty incurred by attempting to "filter" events in the traffic controller would be high.  A CF team with more knowledge than I have would need to provide you more details and feasibility.

**Comment by jtuchscherer** [comment]
I think it is a common misconception that the firehose needs admin privileges. There is a per-app-firehose endpoint that streams all information about an app (container metrics, network metrics and logs). For that endpoint, you don't need admin privileges - just access to the app. The CF Nozzle plugin uses that endpoint when you call it with `cf app-nozzle`.

I created #3 to demonstrate that the Top Plugin can work without admin rights. Here is a screenshot from my PWS account (where I am NOT an admin):

<img width="1637" alt="screen shot 2017-01-03 at 12 44 14 pm" src="https://cloud.githubusercontent.com/assets/428720/21606817/5f61f0f0-d1b2-11e6-9427-4be8fbf55b9c.png">

**Comment by kkellner** [comment]
I like the concept of not requiring admin privileges however I'm concerned about resource consumption using StreamWithoutReconnect.   Since this API must be called per app, each call opens a socket connection to the go-router.   I assume the go-router then opens a connection to the traffic-controller to stream the events back through the go-router to the client.

This means that if a user has visibility to 100 apps, `top` would end up creating 100 persistent socket connections for 1 running instance of `top`.   We then multiple that by several users on a team that might be using `top` and we end up consuming a lot of resources.  The last thing I want is `top` to be the source of problems for a foundation.   Thoughts?

**Comment by jtuchscherer** [comment]
My gut feel tells me that this would be okay.

I doubt that people with access to large amount of apps would use the `cf top` command. They probably have (or should have) a monitoring setup with a real monitoring solution (e.g. prometheus). Even if they open `cf top`, I assume it would not be for a long lived session.  

If this plugin were to bring down the gorouter, it also says two things about the CF installation as a whole: a) the gorouters were not ready for a traffic surge and probably have to be scaled up, and b) the users are missing a good way to monitor their applications - so maybe the CF operators should enable some of the proven monitoring solutions for their CF users. 

If you are still concerned, there are a few ways on how to limit the risk:

1. Warning text to inform the user about the potential risk of opening too many websockets
1. User has to provide a white list of apps to be included in the output - only for those the firehose would be opened
1. If user has admin right, use the admin firehose endpoint

**Comment by kkellner** [comment]
In the environments I've been in developers would often run multiple `cf logs` against different apps and let the run for days.  So I'll assume that `cf top` could be used in that same way.   I'll figure out how to limit the amount of apps a non-admin can stream.  For uses of type admin / `doppler.firehose` I'll use the firehose. 

@jtuchscherer Do you know a way to test if user has admin right / `doppler.firehose` permission?

**Comment by jtuchscherer** [comment]
@kkellner I threw together a quick fix for the plugin to toggle the logic based on user privileges.

If the user has `doppler.firehose` scope, then open the number of requested firehose connection (default: 2) to the generic firehose endpoint.

If the user does not have the `doppler.firehose` scope, then open one nozzle per app.
