### ISSUE TITLE
Cell Stats not working for a new foundation

### ISSUE THREAD

**Issue by ichandan16** [ECSTeam/cloudfoundry-top-plugin#4]
Hi ECS team,

We are not getting Cell Stats or Capacity Plan info for a newly installed foundation.
The ERT version is 1.7.35.

Attached the screenshot.

![cf_top_issue](https://cloud.githubusercontent.com/assets/9046793/23367649/ff324d40-fcd8-11e6-997a-21162f46ca8b.png)

Thanks,
Chandan

**Comment by kkellner** [comment]
Can you open the log window (CTRL-D after cf top startup) and send a screenshot of the screen?   Also, you you try using the nozzle plugin and see if you are getting container metrics?   (e.g.,  cf nozzle -filter ContainerMetric)

**Comment by ichandan16** [comment]
I did `cf nozzle` and hit enter to collect all the log types. I got only `ValueMetric` and `CounterEvent`.

**Comment by akoranne** [comment]
What user are you running the `cf top` with? 
Does the user have `admin` privileges?

**Comment by ichandan16** [comment]
I am running as admin user for CF foundation. We have 8 foundations with ERT-1.7.35. This plugin works fine with foundations having more than 5 Diego cells but in this case which is a new foundation, it fails to pull Cell Stats.

Thanks,
Chandan

**Comment by kkellner** [comment]
So something is odd -- cf nozzle should return container metrics every 30 seconds --- assuming you have running applications.   I can see you have 14 apps deployed but are they "started" AND running?  Or are they crashing / failed?

**Comment by akoranne** [comment]
Can you review the privileges assigned to the firehose nozzle user?

```
    $> uaac token client get admin -s [admin client secret]
    $> uaac user get [firehose nozzle user] | grep -i display
```

**Comment by kkellner** [comment]
Closing issue as there was no response from reporter.
