### ISSUE TITLE
Crashes Screen - include the Cell IP?

### ISSUE THREAD

**Issue by jregehr** [ECSTeam/cloudfoundry-top-plugin#6]
The App Crash screen includes the index # - could it also include the Cell IP?

**Comment by kkellner** [comment]
I agree that would be nice information to have however the Cloud Controller API that provides the crash information (/v2/events) does not include this information.  So the only way to capture it would be if `cf top` was running at the time of the crash in which case it could be calculated.   However this would mean there would be different information display depending on when the crash occurred which I was trying to avoid.
