### ISSUE TITLE
isolation segment screen is taking too much space

### ISSUE THREAD

**Issue by avasseur-pivotal** [ECSTeam/cloudfoundry-top-plugin#7]
I find that when I have 3 isolation segments in addition to the default shared - the Cell part at the top of all the screen is taking far too much space.
Can it be a specific screen or something that can be toggled to view/hide, or may be even filtered as well in someway ?

see screenshot of overview + of app detail as example
<img width="647" alt="screen shot 2017-06-15 at 23 07 55" src="https://user-images.githubusercontent.com/5575656/27201880-9ad7f308-521f-11e7-99bc-b87d935a96db.png">

**Comment by kkellner** [comment]
Remember that help (h command) is your friend.    In this case the command to toggle the header is "H" (shift-H).

**Comment by avasseur-pivotal** [comment]
So nice!
thanks again for such a great plugin!
