### ISSUE TITLE
ARM Architecture Support

### ISSUE THREAD

**Issue by leebickmtu** [ECSTeam/cloudfoundry-top-plugin#8]
Please support ARMv7 architecture with a binary build.

**Comment by leebickmtu** [comment]
Sorry, meant ARMv6, supports more systems that way.

**Comment by kkellner** [comment]
ARMv6 on what OS?  Linux?   Is this for Raspberry Pi?

**Comment by leebickmtu** [comment]
Yes, it is Raspbian Linux on a Pi Zero that I am trying to run it on.

**Comment by kkellner** [comment]
I'm not seeing any other cf plugins supporting ARM.   Do you know of any?
https://plugins.cloudfoundry.org/

If fact I'm not seeing an official cf client for ARM:  https://github.com/cloudfoundry/cli/releases

**Comment by leebickmtu** [comment]
Not sure about an official cf-cli build, but "go get code.cloudfoundry.org/cli" will successfully build it on ARM Linux. I have it running right now.

**Comment by kkellner** [comment]
I'm curious, what is your use case for running cf (and cf top) on a Pi?

**Comment by leebickmtu** [comment]
I want to leave it running on a wall mounted display in our office building for quick stats about our CF deployed apps.

**Comment by kkellner** [comment]
OK, that was going to be my guess as we were thinking about doing the same thing.  Let me look into it.

**Comment by leebickmtu** [comment]
Thanks

**Comment by kkellner** [comment]
I created a arm6 binary.  I do not have a pi handy to test.   Can you test and let me know if it works?
https://github.com/ECSTeam/cloudfoundry-top-plugin/releases/tag/v0.8.5

**Comment by leebickmtu** [comment]
It is working, thank you for getting this so quick.

**Comment by kkellner** [comment]
Great to hear it's working.   If you can report back after a few days and let me know if the pi is able to keep up and your events-per-second value on your monitored environment.   I would be worried that it will not be able to keep up.   On busy environments (e.g., > 30,000 events per second) I've seen it exceed 1GigE network bandwidth which is why I often recommend running `cf top` on a VM close to the monitored environment on a 10GigE network.

**Comment by leebickmtu** [comment]
It's a fairly low traffic environment. 1440 events over the 14 minutes I've had it running now.
